# This is the practice on numpy

here is a useful reference :
http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [1]:
import numpy as np

# 1. Reverse a vector (first element becomes last)

In [10]:
x = np.arange(50)
              #complete here ,to reverse x
x[::-1]
# for i in range(25):
#     temp = x[i]
#     x[i] = x[49-i]
#     x[49-i] = temp
# print(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 2. Create a 2d array with 1 on the border and 0 inside 

In [8]:
x = np.ones((10,10))
                    #complete here ,to make output as following sample 
x[1:-1,1:-1] = 0
print(x)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


# 3. Multiply a 2x2 matrix (a) by a 2x2 matrix(b)  (real matrix product)

In [13]:
a = np.ones((2,2))
b = np.ones((2,2))

                   #complete here ,to make output as following sample 
c = a.dot(b)
print(c)

[[ 2.  2.]
 [ 2.  2.]]


# 4. Create random vector of size 10 and replace the maximum value by 0

In [23]:
Z = np.random.random(10)
print(Z)
print(Z.argmax())
Z[Z.argmax()]  = 0                    #complete here ,to make output as following sample 
print(Z)

[ 0.65834679  0.02437291  0.81760863  0.12202807  0.24716368  0.82623669
  0.81003     0.84836114  0.96015378  0.53361291]
8
[ 0.65834679  0.02437291  0.81760863  0.12202807  0.24716368  0.82623669
  0.81003     0.84836114  0.          0.53361291]


# 5. How to find the closest value (to a given scalar) in an array? 

In [21]:
z = np.arange(10)
v = np.random.uniform(0,10)
print(z)
print(v)                
idx = (np.abs(z-v)).argmin()                           #complete here ,to make output as following sample
print(z[idx])

[0 1 2 3 4 5 6 7 8 9]
0.19459574920018374
0


# 6. Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
Z = np.zeros((8,8),dtype=int)
                           #complete here ,to make output as following sample 
Z[::2,::2] = 1
Z[1::2,1::2] = 1

print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 7. Normalize a 5x5 random matrix 

In [38]:
Z = np.random.random((5,5))
                                 #complete here ,to make output as following sample
max_x = Z.argmax() % 5
max_y = int( Z.argmax()/5)

min_x = Z.argmin() % 5
min_y = int( Z.argmin() /5)


Z = (Z - Z[min_x][min_y])/ Z[max_x][max_y]
print(Z)

[[ 1.44050535  0.29109191  0.26473036  0.35135628  3.25681528]
 [ 0.73242667  0.78887608  1.86444758  1.60249977  1.33299847]
 [ 2.80192402  0.72406949  0.          2.57091376  3.3026776 ]
 [ 1.11982276  2.81693493  0.95118237  0.42719677  2.36994309]
 [ 1.29081457  3.14916429  0.86847496  0.06638198  1.34773692]]


# 8. Extract the integer part of a random array using 5 different methods 

In [39]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 0.  2.  9.  9.  9.  5.  0.  4.  1.  4.]
[ 0.  2.  9.  9.  9.  5.  0.  4.  1.  4.]
[ 0.  2.  9.  9.  9.  5.  0.  4.  1.  4.]
[0 2 9 9 9 5 0 4 1 4]
[ 0.  2.  9.  9.  9.  5.  0.  4.  1.  4.]


# 9. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [53]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)                          #complete here ,to make output as following sample 
T = np.arctan2(Y,X)
X = np.ones((10,2))
X[:, 0] = R
X[:, 1] = T
print(X)


[[ 0.1901542   0.29568578]
 [ 0.05229127  0.39635384]
 [ 0.30446276  0.9158965 ]
 [ 0.88568419  0.55767094]
 [ 0.99788384  0.37921974]
 [ 0.43635466  0.05029289]
 [ 0.67673513  0.05960729]
 [ 0.74205521  0.7809729 ]
 [ 0.83354892  0.54321357]
 [ 0.40777537  0.7850424 ]]
[[ 0.35155185  0.9992902 ]
 [ 0.39978837  1.4396231 ]
 [ 0.96517562  1.24986756]
 [ 1.04662952  0.56193606]
 [ 1.06751101  0.36316792]
 [ 0.43924339  0.11475057]
 [ 0.67935518  0.08785395]
 [ 1.07729504  0.81094544]
 [ 0.99492954  0.57756073]
 [ 0.88463118  1.09172502]]
[[[ 0.35155185  0.39978837  0.96517562  1.04662952  1.06751101  0.43924339
    0.67935518  1.07729504  0.99492954  0.88463118]]

 [[ 0.9992902   1.4396231   1.24986756  0.56193606  0.36316792  0.11475057
    0.08785395  0.81094544  0.57756073  1.09172502]]]


# 10. Tell the difference between view and copy, among b,c,d which is shade copy of a, which is deep copy of a?

In [82]:
#creat a
a = np.array([[1,2,3],[4,5,6]])
# b is another reference object of the array
b = a
#change b
b[0]=0
print("b:")
print(b)
print("a:")
print(a)

# c is the view on piece of a
c = a[:,1]
#change c
c += -1
print("c:")
print (c)
print("a:")
print(a)

# d is a copy of a
d = a.copy()
d -=d
print("d:")
print(d)
print("a:")
print(a)


b:
[[0 0 0]
 [4 5 6]]
a:
[[0 0 0]
 [4 5 6]]
c:
[-1  4]
a:
[[ 0 -1  0]
 [ 4  4  6]]
d:
[[0 0 0]
 [0 0 0]]
a:
[[ 0 -1  0]
 [ 4  4  6]]


Solutions:...